# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e597d5f0f6c53d19a7771bd3f1ac46e913d9dda061f3f388ba339ca33f7df5543026066a85a1e1753a94cca204389cf8764b9f465f5014980a9041a92b40843b

test:
  secret_key_base: 6ce0d54b9149227b90c53c2dc808d80016a6950584d94112fb367f66106215e1b9e299533f3affced225181fd2d5a1b513af8b9730214aa070b6e5a572d8b46d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
